config/routes.rb
Rails.application.routes.draw do

  root 'activities#index'
  get 'statistic' => 'activities#statistics'

  resources :events, only: [:index, :destroy, :create]
  resources :activities

  resources :mediums

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  scope :featured, -> {order('visitors_count DESC')}
  has_many :visitors, through: :histories, counter_cache: true
  has_many :mediums, through: :histories
  has_many :histories, foreign_key: 'activity_id'
  has_many :events

  def proceeds
    (arpu * visitors.count).round
  end

  def find_histories
    histories.where(activity_id: id)
  end

  def medium_id(who_win = first)
    if who_win == 'first'
      find_histories.first.medium_id.to_s
    elsif who_win == 'last'
      find_histories.last.medium_id.to_s
    end
  end


  def filter(who_win = 'first', search = '')
      if search.present?
        search.split("|").include? (medium_title(who_win))
      else
        true
      end
  end




  def medium_title(who_win = 'first')
      case who_win
        when 'first'
          a = find_histories.first.medium_id.to_s
          mediums.where(id: a).first.title

        when 'last'

          a = find_histories.last.medium_id.to_s
          mediums.where(id: a).first.title
        else
          'Все каналы'
      end
  end


  def mediums_count(who_win = first, search = '')
    if search.present?
      splited = search.split("|").map.with_index.each_with_object({}) {|(i, v), h| h[:"#{i}"] = "%#{v}%"}
      criteria = splited.keys.map {|key| "mediums.title LIKE '#{key}' "}.join(' OR ')
      med_id = mediums.where(criteria).first.id
      History.where("medium_id = :med_id AND activity_id = :activity_id ", med_id: med_id, activity_id: id).count
    elsif who_win == 'linear'
      History.where(activity_id: id).count
    else
      History.where(medium_id: medium_id(who_win), activity_id: id).count
    end
  end

  def mediums_proceed(who_win = first)
    (arpu * mediums_count(who_win)).round || 0
  end

  def self.search(search)
    if search
      splited = search.split("|")
      criteria = splited.map {|key| "mediums.title LIKE '%#{key}%' OR activities.title LIKE '%#{key}%' "}.join(' OR ')
      joins(:mediums).where(criteria).distinct
    else
      all
    end
  end

  def self.search_by_medium(search)
    if search
      joins(:mediums).where("mediums.title LIKE :search OR activities.title LIKE :search", search: "%#{search}%").distinct
    else
      all
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  serialize :recurring, Hash
  belongs_to :activity
  has_many :event_exceptions

  def recurring=(value)
    if RecurringSelect.is_valid_rule?(value)
      super(RecurringSelect.dirty_hash_to_rule(value).to_hash)
    else
      super(nil)
    end
  end

  def rule
    IceCube::Rule.from_hash recurring
  end

  def schedule(start)
    schedule = IceCube::Schedule.new(start)
    schedule.add_recurrence_rule(rule)

    event_exceptions.each do |exception|
      schedule.add_exception_time(exception.time)
    end

    schedule
  end

  def calendar_events(start)
    if recurring.empty?
      [self]
    else
      #start_date = start.beginning_of_month.beginning_of_week
      end_date = start.end_of_month.end_of_week
      schedule(start_time).occurrences(end_date).map do |date|
        Event.new(id: id, activity_id: activity_id, start_time: date)
      end
    end
  end
end

app/models/event_exception.rb
class EventException < ActiveRecord::Base
  belongs_to :event
  validates :time, presence: true
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to  :visitor
  belongs_to :activity
  belongs_to :medium
end

app/models/medium.rb
class Medium < ActiveRecord::Base
  include ActionView::Helpers
  has_many :visitors, through: :histories
  has_many :activities, through: :histories
  has_many :histories, foreign_key: 'medium_id'
  self.table_name = 'mediums'

  def activities_proceeds
    summ ||= 0
    medium_activity_ids = 'SELECT activity_id FROM histories WHERE  medium_id = :medium_id'
    medium_activities = activities.where("activity_id IN (#{medium_activity_ids})", medium_id: id)
    medium_activities.each do |medium_activity|
      summ += medium_activity.arpu
    end
    summ.round
  end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_many :mediums, through: :histories
  has_many :activities, through: :histories
  has_many :histories, foreign_key: 'visitor_id'

  def visit_activity(medium, activity)
    histories.create!(medium_id: medium.id, activity_id: activity.id)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @activities = Activity.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(page: params[:page])
  end

  def statistics
    @activities = Activity.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(page: params[:page])
    #@activities = Activity.search_by_medium(params[:search]).order(sort_column + ' ' + sort_direction).paginate(page: params[:page])
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def edit
    @activity = Activity.find(params[:id])
    @event = Event.new(:activity=>@activity)
  end

  def update
    @activity = Activity.find(params[:id])
    if @activity.update_attributes(activity_params)
      flash[:success] = "Изменения сохранены!"
      redirect_to @activity
    else
      render 'edit'
    end
  end

  private
  def sort_column
    Activity.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def activity_params
    params.require(:activity).permit(:title, :price, :logs, :city)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event/event_exceptions_controller.rb
class Event::EventExceptionsController < ApplicationController
  before_action :set_event

  def create
    if @exception = @event.event_exceptions.create(exception_params)
      flash.notice = "Exception added!"
      #redirect_to events_path
    else
      flash.alert = "Unable to add exception"
      #redirect_to @event
    end
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def exception_params
    params.require(:event_exception).permit(:time)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action do
    @activity = Activity.find_by(id: params[:id])
  end

  def index
    @activity = Activity.all
    @events = Event.all
    @calendar_events = @events.flat_map{ |e| e.calendar_events(params.fetch(:start_date, Time.zone.now).to_date) }
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Дата добавлена!' }
        format.json { render :show, status: :created, location: @event }
        format.js
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end


  private
  def event_params
    params.require(:event).permit(:activity_id, :start_time, :recurring)
  end
end

app/controllers/mediums_controller.rb
class MediumsController < ApplicationController
  def index
    @mediums = Medium.all
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction), {:class => css_class}
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/mediums_helper.rb
module MediumsHelper
end

app/helpers/recurring_events_helper.rb
module RecurringEventsHelper
end

app/views/activities/index.html.erb
<div class="input-group">
  <%= form_tag activities_path, :method => 'get', :class => "navbar-form", :role => "search" do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <div>
      <%= text_field_tag :search, params[:search], :class => "form-control", placeholder: 'Введите название экскурсии' %>
    </div>
    <div class="btn_search_activity">
      <%= submit_tag "Поиск", :name => nil, :class => "btn btn-default" %>
    </div>
  <% end %>
</div>
<br>
<table class="table-activities table-bordered table-hover table-responsive">
  <thead>
  <tr>
    <th><%= sortable 'id' %></th>
    <th><%= sortable 'title', 'Экскурсия' %></th>
    <th><%= sortable 'visitors_count', 'Количество посещений' %></th>
    <th><%= sortable 'price', 'Цена' %></th>
    <th><%= sortable 'rating', 'Оценка клиентов' %></th>
    <th>Суммарная выручка</th>
  </tr>
  </thead>
  <% @activities.each do |activity| %>
    <tr>
      <th><%= activity.id %></th>
      <th><%= link_to activity.title, activity %></th>
      <th><%= activity.visitors.count %></th>
      <th><%= activity.price %></th>
      <th><%= activity.rating %></th>
      <th><%= activity.proceeds %></th>
    </tr>
  <% end %>
</table>
<%= will_paginate %>



<section class="recommendations">
  <h2 class="recommendations_city-title">Санкт-Петербург</h2>
  <div class="b-carousel">

    <div class="b-carousel-button-left button default">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </div>
    <div class="b-carousel-button-right button default">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    </div>

    <div class="h-carousel-wrapper">
      <div class="h-carousel-items">
        <div class="b-carousel-block">
          <div class="activity">
            <a href="#" class="a-carousel-image-link">
              <%= image_tag "1.jfif" %>
            </a>
            <a href="#" class="activity_link">
              Автобусная экскурсия в Будапешт
            </a>
            <div class="action_price">Цена за человека 790 ₽</div>
            <div class="star-rating">
              <i class="fa fa-star" data-rating="1"></i>
              <i class="fa fa-star" data-rating="2"></i>
              <i class="fa fa-star" data-rating="3"></i>
              <i class="fa fa-star" data-rating="4"></i>
              <i class="fa fa-star" data-rating="5"></i>
            </div>
          </div>
        </div>

        <div class="b-carousel-block">
          <a href="#" class="a-carousel-image-link">
            <%= image_tag "2.jfif" %>
          </a>
          <a href="#" class="activity_link">
            Экскурсия по дворам в Киото
          </a>
          <div class="action_price">Цена за человека 1290 ₽</div>
          <div class="star-rating">
            <i class="fa fa-star" data-rating="1"></i>
            <i class="fa fa-star" data-rating="2"></i>
            <i class="fa fa-star" data-rating="3"></i>
            <i class="fa fa-star" data-rating="4"></i>
            <i class="fa fa-star" data-rating="5"></i>
          </div>
        </div>

        <div class="b-carousel-block">
          <a href="#" class="a-carousel-image-link">
            <%= image_tag "3.jfif" %>
          </a>
          <a href="#" class="activity_link">
            Прогулки с динозаврами
          </a>
          <div class="action_price">Цена за человека 710 ₽</div>
          <div class="star-rating">
            <i class="fa fa-star" data-rating="1"></i>
            <i class="fa fa-star" data-rating="2"></i>
            <i class="fa fa-star-o" data-rating="3"></i>
            <i class="fa fa-star-o" data-rating="4"></i>
            <i class="fa fa-star-o" data-rating="5"></i>
          </div>
        </div>

        <div class="b-carousel-block">
          <a href="#" class="a-carousel-image-link">
            <%= image_tag "4.jfif" %>
          </a>
          <a href="#" class="activity_link">
            Ишимбай - столица мира
          </a>
          <div class="action_price">Цена за человека 1790 ₽</div>
          <div class="star-rating">
            <i class="fa fa-star" data-rating="1"></i>
            <i class="fa fa-star" data-rating="2"></i>
            <i class="fa fa-star" data-rating="3"></i>
            <i class="fa fa-star" data-rating="4"></i>
            <i class="fa fa-star-o" data-rating="5"></i>
          </div>
        </div>

        <div class="b-carousel-block">
          <a href="#" class="a-carousel-image-link">
            <%= image_tag "5.jfif" %>
          </a>
          <a href="#" class="activity_link">
            Историческая экскурсия в Стамбуле
          </a>
          <div class="action_price">Цена за человека 2390 ₽</div>
          <div class="star-rating">
            <i class="fa fa-star" data-rating="1"></i>
            <i class="fa fa-star" data-rating="2"></i>
            <i class="fa fa-star" data-rating="3"></i>
            <i class="fa fa-star-o" data-rating="4"></i>
            <i class="fa fa-star-o" data-rating="5"></i>
          </div>
        </div>

      </div>
    </div>

  </div>
</section>

<section class="recommendations">
  <h2 class="recommendations_city-title">Москва</h2>
  <div class="b-carousel">

    <div class="b-carousel-button-left button default">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </div>
    <div class="b-carousel-button-right button default">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    </div>

    <div class="h-carousel-wrapper">
      <div class="h-carousel-items">
        <div class="b-carousel-block">
          <div class="activity">
            <a href="#" class="a-carousel-image-link">
              <%= image_tag "1.jfif" %>
            </a>
            <a href="#" class="activity_link">
              Автобусная экскурсия в Будапешт
            </a>
            <div class="action_price">Цена за человека 790 ₽</div>
            <div class="star-rating">
              <i class="fa fa-star" data-rating="1"></i>
              <i class="fa fa-star" data-rating="2"></i>
              <i class="fa fa-star" data-rating="3"></i>
              <i class="fa fa-star" data-rating="4"></i>
              <i class="fa fa-star" data-rating="5"></i>
            </div>
          </div>
        </div>

        <div class="b-carousel-block">
          <a href="#" class="a-carousel-image-link">
            <%= image_tag "2.jfif" %>
          </a>
          <a href="#" class="activity_link">
            Экскурсия по дворам в Киото
          </a>
          <div class="action_price">Цена за человека 1290 ₽</div>
          <div class="star-rating">
            <i class="fa fa-star" data-rating="1"></i>
            <i class="fa fa-star" data-rating="2"></i>
            <i class="fa fa-star" data-rating="3"></i>
            <i class="fa fa-star" data-rating="4"></i>
            <i class="fa fa-star" data-rating="5"></i>
          </div>
        </div>

        <div class="b-carousel-block">
          <a href="#" class="a-carousel-image-link">
            <%= image_tag "3.jfif" %>
          </a>
          <a href="#" class="activity_link">
            Прогулки с динозаврами
          </a>
          <div class="action_price">Цена за человека 710 ₽</div>
          <div class="star-rating">
            <i class="fa fa-star" data-rating="1"></i>
            <i class="fa fa-star" data-rating="2"></i>
            <i class="fa fa-star-o" data-rating="3"></i>
            <i class="fa fa-star-o" data-rating="4"></i>
            <i class="fa fa-star-o" data-rating="5"></i>
          </div>
        </div>

        <div class="b-carousel-block">
          <a href="#" class="a-carousel-image-link">
            <%= image_tag "4.jfif" %>
          </a>
          <a href="#" class="activity_link">
            Ишимбай - столица мира
          </a>
          <div class="action_price">Цена за человека 1790 ₽</div>
          <div class="star-rating">
            <i class="fa fa-star" data-rating="1"></i>
            <i class="fa fa-star" data-rating="2"></i>
            <i class="fa fa-star" data-rating="3"></i>
            <i class="fa fa-star" data-rating="4"></i>
            <i class="fa fa-star-o" data-rating="5"></i>
          </div>
        </div>

        <div class="b-carousel-block">
          <a href="#" class="a-carousel-image-link">
            <%= image_tag "5.jfif" %>
          </a>
          <a href="#" class="activity_link">
            Историческая экскурсия в Стамбуле
          </a>
          <div class="action_price">Цена за человека 2390 ₽</div>
          <div class="star-rating">
            <i class="fa fa-star" data-rating="1"></i>
            <i class="fa fa-star" data-rating="2"></i>
            <i class="fa fa-star" data-rating="3"></i>
            <i class="fa fa-star-o" data-rating="4"></i>
            <i class="fa fa-star-o" data-rating="5"></i>
          </div>
        </div>

      </div>
    </div>

  </div>
</section>

app/views/activities/show.html.erb
<section class="activity_information">
  <h1>Информация о экскурсии</h1>
  <h2><%= @activity.title %></h2>  <%= link_to 'Редактировать экскурсию', edit_activity_path, class: "btn btn-link", role: 'button' %>

  <table class="table-activities-info table-bordered table-hover table-responsive">
    <thead>
    <tr>
      <th>Данные</th>
      <th>Значения</th>
    </tr>
    </thead>
    <tr>
      <th>Средний доход с просмотра</th>
      <th><%= @activity.arpu %> рублей</th>
    </tr>
    <tr>
      <th>Город</th>
      <th><%= @activity.city %></th>
    </tr>
    <tr>
      <th>Количество посетителей</th>
      <th><%= @activity.visitors_count %> человек</th>
    </tr>
    <tr>
      <th>Цена</th>
      <th><%= @activity.price %></th>
    </tr>
    <tr>
      <th>Оценка посетителей</th>
      <th><%= @activity.rating %></th>
    </tr>
  </table>
</section>


<section class="also_seen">
  <h3>Также с этой экскурсией смотрели:</h3>
  <div class="activity-seen">
    <a href="#" class="a-carousel-image-link">
      <%= image_tag "1.jfif" %>
    </a>
    <a href="#" class="activity_link">
      Автобусная экскурсия в Будапешт
    </a>
    <div class="action_price">Цена за человека 790 &#8399;</div>
    <div class="star-rating">
      <i class="fa fa-star" data-rating="1"></i>
      <i class="fa fa-star" data-rating="2"></i>
      <i class="fa fa-star" data-rating="3"></i>
      <i class="fa fa-star" data-rating="4"></i>
      <i class="fa fa-star" data-rating="5"></i>
    </div>
  </div>
  <div class="activity-seen">
    <a href="#" class="a-carousel-image-link">
      <%= image_tag "2.jfif" %>
    </a>
    <a href="#" class="activity_link">
      Экскурсия по дворам в Киото
    </a>
    <div class="action_price">Цена за человека 790 &#8399;</div>
    <div class="star-rating">
      <i class="fa fa-star" data-rating="1"></i>
      <i class="fa fa-star" data-rating="2"></i>
      <i class="fa fa-star" data-rating="3"></i>
      <i class="fa fa-star" data-rating="4"></i>
      <i class="fa fa-star" data-rating="5"></i>
    </div>
  </div>
  <div class="activity-seen">
    <a href="#" class="a-carousel-image-link">
      <%= image_tag "3.jfif" %>
    </a>
    <a href="#" class="activity_link">
      Ишимбай - столица мира
    </a>
    <div class="action_price">Цена за человека 790 &#8399;</div>
    <div class="star-rating">
      <i class="fa fa-star" data-rating="1"></i>
      <i class="fa fa-star" data-rating="2"></i>
      <i class="fa fa-star" data-rating="3"></i>
      <i class="fa fa-star" data-rating="4"></i>
      <i class="fa fa-star" data-rating="5"></i>
    </div>
  </div>
  <div class="activity-seen">
    <a href="#" class="a-carousel-image-link">
      <%= image_tag "4.jfif" %>
    </a>
    <a href="#" class="activity_link">
      Историческая экскурсия в Стамбуле
    </a>
    <div class="action_price">Цена за человека 790 &#8399;</div>
    <div class="star-rating">
      <i class="fa fa-star" data-rating="1"></i>
      <i class="fa fa-star" data-rating="2"></i>
      <i class="fa fa-star" data-rating="3"></i>
      <i class="fa fa-star" data-rating="4"></i>
      <i class="fa fa-star" data-rating="5"></i>
    </div>
  </div>
  <div class="activity-seen">
    <a href="#" class="a-carousel-image-link">
      <%= image_tag "5.jfif" %>
    </a>
    <a href="#" class="activity_link">
      Вечерняя экскурсия в Орлеане
    </a>
    <div class="action_price">Цена за человека 790 &#8399;</div>
    <div class="star-rating">
      <i class="fa fa-star" data-rating="1"></i>
      <i class="fa fa-star" data-rating="2"></i>
      <i class="fa fa-star" data-rating="3"></i>
      <i class="fa fa-star" data-rating="4"></i>
      <i class="fa fa-star" data-rating="5"></i>
    </div>
  </div>
  <div class="activity-seen">
    <a href="#" class="a-carousel-image-link">
      <%= image_tag "6.jfif" %>
    </a>
    <a href="#" class="activity_link">
      Ночная экскурсия по Казани
    </a>
    <div class="action_price">Цена за человека 790 &#8399;</div>
    <div class="star-rating">
      <i class="fa fa-star" data-rating="1"></i>
      <i class="fa fa-star" data-rating="2"></i>
      <i class="fa fa-star" data-rating="3"></i>
      <i class="fa fa-star" data-rating="4"></i>
      <i class="fa fa-star" data-rating="5"></i>
    </div>
  </div>
</section>

app/views/activities/statistics.html.erb
<div class="input-group">

  <%= form_tag statistic_path, :method => 'get', :class => "navbar-form", :role => "search", id: 'statistics_search' do %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>
    <p>
      <%= text_field_tag :search, params[:search], placeholder: 'Введите название канала', :class => "form-control" %>
    </p>
    <br>
    <h4>Модель атрибуции:</h4>
    <div class="atribution_radio">

      <label for="who_win">
        <%= radio_button_tag :who_win, "first", :class => 'atribution_radio', id:"who_win_first" %>
        Посетитель засчитывается к каналу, с которого было совершено первое посещение(First)
      </label>
      <label for="who_win">
        <%= radio_button_tag :who_win, "last", :class => 'atribution_radio', id:"who_win_last"  %>
        Посетитель засчитывается к каналу, с которого было совершено последнее посещение(Last)
      </label>
      <label for="who_win">
        <%= radio_button_tag :who_win, "linear", :class => 'atribution_radio', id:"who_win_linear"  %>
        Посетитель засчитывается ко всем каналам, с которых были переходы(Linear)
      </label>
      <div class="input-group-btn">
        <%= submit_tag "Поиск", :name => nil, :class => "btn btn-default" %>
      </div>
    </div>

  <% end %>
</div>

<div class="statistics_table">
  <% if !params[:who_win].present?
       params[:who_win] = 'linear'
     end %>


  <%= render 'layouts/statistics_table' %>
</div>
<%= will_paginate %>


<script>

    // $('#who_win_first').click(function () {
    //     alert('клик на первом');
    //     localStorage.setItem('who_win_first', checked);
    // });
    //
    // $('#who_win_last').click(function () {
    //
    //     localStorage.setItem('who_win_last', checked);
    // });
    //
    // $('#who_win_linear').click(function () {
    //     localStorage.setItem('who_win_linear', checked);
    // });

    var url = new URL(location.href);
    var who_win_radio = url.searchParams.get("who_win");

    switch (who_win_radio) {
        case 'first':
            $('#who_win_first').prop('checked', true);
            break;
        case 'last':
            $('#who_win_last').prop('checked', true);
            break;
        case 'linear':
            $('#who_win_linear').prop('checked', true);
            break;
    }


</script>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>Events</h1>

<%= month_calendar events: @calendar_events do |day, events| %>
  <div><strong><%= day.to_s(:long) %></strong></div>
  <% events.each do |event| %>
    <div>
      <%= link_to event.activity.title, activity_path(event.activity.id) %>
    </div>
  <% end %>
<% end %>

<table>
  <thead>
  <tr>
    <th>Activity ID</th>
    <th>Дата и время</th>
    <th>Повторение</th>

  </tr>
  </thead>

  <tbody>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.activity_id %></td>
      <td><%= event.start_time %></td>
      <td><%= event.recurring %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "Учет атрибуции", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Экскурсии", root_path %></li>
        <li><%= link_to "Каналы", mediums_path %></li>
        <li><%= link_to "Статистика", statistic_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_statistics_table.html.erb
<table class="table-bordered table-hover">
  <tr>
    <th><%= link_to 'ID', :sort => 'id' %></th>
    <th><%= link_to 'Экскурсия', :sort => 'title' %></th>
    <th>Канал</th>
    <th>Количество посетителей</th>
    <th>Выручка</th>
  </tr>

  <%  @activities.each do |activity| %>

    <%if activity.filter(params[:who_win], params[:search]) %>
        <tr>
          <th><%= activity.id %></th>
          <th><%= link_to activity.title, activity %></th>
          <th><%= activity.medium_title(params[:who_win]) %></th>
          <th><%= activity.mediums_count(params[:who_win], params[:search]) %></th>
          <th><%= activity.mediums_proceed(params[:who_win]) %></th>
        </tr>
    <% end %>

  <% end %>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atribut</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://unpkg.com/vue"></script>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic"
        rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

</head>
<body>

<%= render 'layouts/header' %>

<div class="container">

    <%= yield %>

  <%= debug(params) if Rails.env.development? %>
</div>
</body>



</html>

app/views/mediums/index.html.erb
<h1>Каналы</h1>
<table class="table-bordered table-hover mediums">
  <tr>
    <th>ID</th>
    <th>Наименование канала</th>
    <th>Количество посетителей</th>
    <th>Суммарная выручка</th>
  </tr>
  <% @mediums.each do |medium| %>
      <tr>
        <th><%= medium.id %></th>
        <th><%= medium.title %></th>
        <th><%= medium.visitors.count %></th>
        <th><%= medium.activities_proceeds %></th>
      </tr>
  <% end %>
</table>